//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace paginaWeb.paginasFabricaFatay
{


    public partial class historial_de_stock_fabrica_fatay
    {
    }
}
